### PR TITLE
Sharing calc additions

### LINKED ISSUE #42: Any way to resume sharing calculations?
first off, thank you for this tool, it has made many things easier for me. 

I am using the `sfdx texei:sharingcalc:suspend` command and wondering if there is any way to resume sharing calculations?

`sfdx texei:sharingcalc:resume` for example

### PR DESCRIPTION
**Pull request by kylethornton**
Closes #42 

This adds the ability to: 

- resume group membership or sharing rule calculations. 
  - When resuming group calculations the "Yes" option is chosen on the pop up dialog

- recalculate sharing rules

### CODE REVIEW

**Comment by kylethornton** [comment]
@FabienTaillon I have added another commit after realizing the script will hang if the button click fails. this now wraps that attempt in a try catch and alerts to what the issue is.

**Comment by kylethornton** [comment]
Hi @FabienTaillon any chance you could have a look at this today? Hoping to get it in so I can continue developing a script that isn't reliant on my local install.

**Comment by FabienTaillon** [comment]
@kylethornton  doing it right now.

**Comment by kylethornton** [comment]
Thanks. happy to make any necessary updates!

**Comment by FabienTaillon** [comment]
Thank you ! The new version has been published to npm, so you should be able to run `sfdx update` to get the latest version with your additions.

**Pull request merged**
