### PR TITLE
Namespace filter , ProjectId attribute support, Manage Package Installation

### PR DESCRIPTION
**Pull request by dieffrei**
- I a project sometimes is not interesting to install some namespaces package. Now using the flag ```-- namespaces ns1,ns2``` we can do it;
- Now it works using package or PackageId attributes

### CODE REVIEW

**Comment by Xixiao007** [comment]
is somebody accepting this pull request?

**Comment by FabienTaillon** [comment]
Sorry, this was on my todo list but never took the time to review it. Will do it this week. I also really need to take some time to look at how to write tests, to make reviews easier.

**Comment by Xixiao007** [comment]
@FabienTaillon ahh, I see! Take your time :).

I remember John Daniel said he had a pull request here with a feature of "prevent to install more than once a package", which seems also being part of this pull request.
No idea what is his progress.

**Comment by FabienTaillon** [comment]
FYI @ImJohnMDaniel

**Comment by ImJohnMDaniel** [comment]
@dieffrei -- I am not certain that I understand what you are trying to do on this change.  Is it to prevent the installation of packages with namespaces?

@Xixiao007 and @FabienTaillon -- I still have some more work on my PR.  Hopefully, will get some time this weekend to work on it.

**Comment by dieffrei** [comment]
@ImJohnMDaniel Hi guys!
So we have multiple namespaces, then depends of project we only want to install some specific namespace dependencies.
If I want to create a new scratch org for the finance project (ns_fin), I want to push the source code to the scratch org and not install the dependency packages. But I still need to install dependencies from the another projects (diferent namespaces e.g ns_commons, ns_logistic)...

This is a piece of our new scratch org script:
```
sfdx force:org:create -s -f ./config/project-scratch-def.json --durationdays 30 -w 10 -a $1
sfdx guidion:build:fix
sfdx texei:package:dependencies:install --namespaces gui_utl,fsl,gui_commons  --noprompt -u $1
sfdx force:source:push -f -u $1
```

**Comment by dieffrei** [comment]
Another point it prevents to install the same package more than once

**Comment by dieffrei** [comment]
Maybe a new good feature, I would like to build is create a report between the diferences between the sfdx-project dependencies definition vs salesforce environment.
Currently we have 35 packages and 5 namespaces.

**Comment by FabienTaillon** [comment]
Something I don't get is, if it's a dependency, should these package be mandatory to push your code ?
If not, shouldn't they be removed from your dependency list ?

**Comment by dieffrei** [comment]
@FabienTaillon Here more about our use case:

- **(ns_commons)** Commons Namespace (sfdx-project):
-- it is in another repo/ another project

```
 {
            "path": "collection",
            "package": "collection",
            "versionName": "ver 1.0",
            "versionNumber": "1.0.0.NEXT"
}
```

- **(ns_finance)** Finance Namespace (sfdx-project):
** it is in another repo/ another project

````
 {
            "path": "package-1",
            "package": "package-1",
            "versionName": "ver 1.0",
            "versionNumber": "1.0.0.NEXT",
            "dependencies": [
                {
                    "packageId": "ns_commons.collection",
                    "versionNumber": "1.0.0.LATEST"
                },
}
 {
            "path": "package-2",
            "package": "package-2",
            "versionName": "ver 1.0",
            "versionNumber": "1.0.0.NEXT",
            "dependencies": [
                {
                    "packageId": "ns_commons.collection",
                    "versionNumber": "1.0.0.LATEST"
                },
                {
                    "packageId": "package-1",
                    "versionNumber": "1.0.0.LATEST"
                }
}
```
Then in this case, on the ns_finance project, I don't want to install the package-1 dependency but I want to push the code to scratch org.
If I run the texei standard version now, it will to install package-1 (I don't want it).

**Comment by ImJohnMDaniel** [comment]
@dieffrei -- So, the use case is if you have setup your project with multiple package directories and you may want to work with only one package directory at the moment.  Thus you would only need the dependencies for that one package directory.  Your change provides an easy way to install only the dependencies from a specific namespace and not all dependencies from all packages listed in the sfdx-project.json. 

Is that correct?

**Comment by FabienTaillon** [comment]
@dieffrei If I understand correctly, you have 2 packages (package-1 and package-2) in one repo, right ?
How do you manage the default package ? 

When developing a new feature, you create a scratch org, and push the source from both packages. So even when doing developments for package-2, package-1 metadata is just pushed, not installed as a package, is that your use case ?

When pulling new metadata, it will be pulled in the default package, and then do you reorder them manually in the correct package ?

At the beginning I wanted to add a "package" flag, so that you could list which dependencies you want to install.
So --package package-1 would only install ns_commons.collection, whereas --package package-2 would install both ns_commons.collection and package-1. 

Is that what you're looking for ?

**Comment by FabienTaillon** [comment]
We discussed this exact use case with @ImJohnMDaniel last year, and decided not to add this flag just because of these issues and having to manually reorder the metadata, but I'm totally open to add them again. I would prefer using "package" over "namespace", as I'm not using namespace on my packages, but would still be able to filter with package name/id. What do you think ?

**Comment by dieffrei** [comment]
Another important information about this PR:
This feature doesn't have breaking changes, If you doesn't supply a --namespace the command will install all the packages on the project file.

**Comment by FabienTaillon** [comment]
I'm still a little bit confused by the name "namespace" as I'm not using namespace, and thus I would not be able to filter that way.

If I replace the `namespace` flag by a `package` one, that would look for the package alias or package id, would it be the

You would do:
`sfdx texei:package:dependencies:install --package package-1`

And then only the dependencies of this package would be installed, and you would be able to push the remaining code as you wished.

On my own use case, not using namespace, I would be able to use the feature too.

What do you think ?

**Comment by FabienTaillon** [comment]
@dieffrei any thoughts on this, would that solve your use case too ?

**Pull request merged**
